name: "Package check"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  qemux86:
    name: "build"
    env:
      DISTRO: scatest
      MACHINE: qemux86
      SCABRANCH: staging
      ENABLEMETAOE: 1
      ENABLEMETACLANG: 1
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

    runs-on: ubuntu-latest

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        WEB_REPOSITORY: priv-kweihmann/priv-kweihmann.github.io
      volumes:
        - ${{ github.workspace }}:/opt/build

    steps:
      - name: Check out poky
        run: |
          git clone git://git.yoctoproject.org/poky.git/ -b master ${WORKSPACE}/poky
        shell: bash
      - name: Check out meta-sca
        run: |
          git clone https://github.com/priv-kweihmann/meta-sca.git -b $SCABRANCH ${WORKSPACE}/meta-sca
      - if: env.ENABLEMETAOE == '1'
        name: Check out meta-oe
        run: |
          git clone git://git.openembedded.org/meta-openembedded -b master ${WORKSPACE}/meta-oe
        shell: bash
      - if: env.ENABLEMETACLANG == '1'
        name: Check out meta-clang
        run: |
          git clone https://github.com/kraj/meta-clang.git -b master ${WORKSPACE}/meta-clang
      - name: Setup poky
        run: |
          cd ${WORKSPACE} 
          source poky/oe-init-build-env
        shell: bash
      - name: add meta-sca
        run: |
          cd ${WORKSPACE}
          source poky/oe-init-build-env
          bitbake-layers add-layer ${WORKSPACE}/meta-sca
        shell: bash
      - if: env.ENABLEMETAOE == '1'
        name: add meta-oe
        run: |
          cd ${WORKSPACE}
          source poky/oe-init-build-env
          bitbake-layers add-layer ${WORKSPACE}/meta-oe/meta-oe
        shell: bash
      - if: env.ENABLEMETACLANG == '1'
        name: add meta-clang
        run: |
          cd ${WORKSPACE}
          source poky/oe-init-build-env
          bitbake-layers add-layer ${WORKSPACE}/meta-clang
        shell: bash
      - name: perform package check
        run: |
          cd ${WORKSPACE}
          source poky/oe-init-build-env
          $(WORKSPACE)/meta-sca/scripts/check_pkgs.py --blacklistfile=$(WORKSPACE)/meta-sca/recipes-sca-test/blacklist.txt priv-kweihmann ${{ secrets.WEBDEPLOY }}
        shell: bash
