name: "Package check"

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  qemux86:
    name: "build"
    env:
      DISTRO: scatest
      MACHINE: qemux86
      SCABRANCH: staging
      ENABLEMETAOE: 1
      ENABLEMETACLANG: 1
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

    runs-on: ubuntu-latest

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        WEB_REPOSITORY: priv-kweihmann/priv-kweihmann.github.io
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged

    steps:
      - name: Prep container
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288 2>&1
          sudo chown yoctouser:yoctouser ${WORKSPACE} 2>&1
      - name: Check out poky
        run: |
          git clone git://git.yoctoproject.org/poky.git/ -b master ${WORKSPACE}/poky 2>&1
        shell: bash
      - name: Check out meta-sca
        run: |
          git clone https://github.com/priv-kweihmann/meta-sca.git -b $SCABRANCH ${WORKSPACE}/meta-sca 2>&1
      - if: env.ENABLEMETAOE == '1'
        name: Check out meta-oe
        run: |
          git clone git://git.openembedded.org/meta-openembedded -b master ${WORKSPACE}/meta-oe 2>&1
        shell: bash
      - if: env.ENABLEMETACLANG == '1'
        name: Check out meta-clang
        run: |
          git clone https://github.com/kraj/meta-clang.git -b master ${WORKSPACE}/meta-clang 2>&1
      - name: Setup poky
        run: |
          cd ${WORKSPACE} 
          source poky/oe-init-build-env 2>&1 && rm -f bitbake.sock 2>&1 && rm -f bitbake.lock 2>&1
        shell: bash
      - name: add meta-sca
        run: |
          cd ${WORKSPACE}
          source poky/oe-init-build-env 2>&1 && rm -f bitbake.sock 2>&1 && rm -f bitbake.lock 2>&1
          bitbake-layers add-layer ${WORKSPACE}/meta-sca 2>&1
        shell: bash
      - if: env.ENABLEMETAOE == '1'
        name: add meta-oe
        run: |
          cd ${WORKSPACE}
          source poky/oe-init-build-env 2>&1 && rm -f bitbake.sock 2>&1 && rm -f bitbake.lock 2>&1
          bitbake-layers add-layer ${WORKSPACE}/meta-oe/meta-oe 2>&1
        shell: bash
      - if: env.ENABLEMETACLANG == '1'
        name: add meta-clang
        run: |
          cd ${WORKSPACE}
          source poky/oe-init-build-env 2>&1 && rm -f bitbake.sock 2>&1 && rm -f bitbake.lock 2>&1
          bitbake-layers add-layer ${WORKSPACE}/meta-clang 2>&1
        shell: bash
      - name: prepare local.conf
        run: |
          cd ${WORKSPACE}
          source poky/oe-init-build-env 2>&1 && rm -f bitbake.sock 2>&1 && rm -f bitbake.lock 2>&1
          echo 'BB_DANGLINGAPPENDS_WARNONLY = "1"' >> conf/local.conf
        shell: bash
      - name: perform package check
        run: |
          cd ${WORKSPACE}
          source poky/oe-init-build-env 2>&1 && rm -f bitbake.sock 2>&1 && rm -f bitbake.lock 2>&1
          ${WORKSPACE}/meta-sca/scripts/check_pkgs.py --blacklistfile=${WORKSPACE}/meta-sca/scripts/blacklist.txt priv-kweihmann ${{ secrets.WEBDEPLOY }} 2>&1
        shell: bash
